// Mocks generated by Mockito 5.0.3 from annotations
// in my_musical_repertoire/test/features/piece/domain/usecases/piece_add_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:my_musical_repertoire/features/piece/domain/entities/piece_entity.dart'
    as _i2;
import 'package:my_musical_repertoire/features/piece/domain/repositories/piece_repository.dart'
    as _i3;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakePieceEntity extends _i1.Fake implements _i2.PieceEntity {}

/// A class which mocks [PieceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPieceRepository extends _i1.Mock implements _i3.PieceRepository {
  MockPieceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PieceEntity> addPiece(_i2.PieceEntity? piece) =>
      (super.noSuchMethod(Invocation.method(#addPiece, [piece]),
              returnValue: Future.value(_FakePieceEntity()))
          as _i4.Future<_i2.PieceEntity>);
  @override
  _i4.Future<_i2.PieceEntity> updatePiece(_i2.PieceEntity? piece) =>
      (super.noSuchMethod(Invocation.method(#updatePiece, [piece]),
              returnValue: Future.value(_FakePieceEntity()))
          as _i4.Future<_i2.PieceEntity>);
  @override
  _i4.Future<String> removePiece(String? id) =>
      (super.noSuchMethod(Invocation.method(#removePiece, [id]),
          returnValue: Future.value('')) as _i4.Future<String>);
  @override
  _i4.Future<List<_i2.PieceEntity>> getPieces() =>
      (super.noSuchMethod(Invocation.method(#getPieces, []),
              returnValue: Future.value(<_i2.PieceEntity>[]))
          as _i4.Future<List<_i2.PieceEntity>>);
}
