name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to prod
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Yarn install
        uses: borales/actions-yarn@v5
        with:
          cmd: install

      - name: Export environment variables
        run: echo "${{ secrets.ENV }}" > .env.local

      - name: Build web
        uses: borales/actions-yarn@v5
        with:
          cmd: build:web

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: my-musical-repertoire
          workload_identity_provider: projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github/providers/my-musical-repertoire

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@13

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project my-musical-repertoire

