name: PR - Lint, build and deploy to dev

on:
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build_deploy:
    name: Lint, build and deploy to dev
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Yarn install
        uses: borales/actions-yarn@v5
        with:
          cmd: install

      - name: Lint
        uses: borales/actions-yarn@v5
        with:
          cmd: lint

      - name: Export environment variables
        run: echo "${{ secrets.ENV }}" > .env.local

      - name: Build web
        uses: borales/actions-yarn@v5
        with:
          cmd: build:web

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: my-musical-repertoire-dev
          workload_identity_provider: projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github/providers/my-musical-repertoire

      - name: Deploy to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: dist
          destination: ${{ secrets.GCS_BUCKET_NAME }}
          process_gcloudignore: false
          parent: false
